default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index"}
    methods: GET

user_login:
    path: /login
    defaults: { _controller: "AppBundle:User:login" }
    methods: POST

user_new:
    path: /user/new
    defaults: { _controller: "AppBundle:User:new" }
    methods: POST

Commande_list:
    path: /orders/list
    defaults: { _controller: "AppBundle:Order:orders"}
    methods: POST

Commande_new:
    path: /orders/new
    defaults: { _controller: "AppBundle:Order:new" }
    methods: POST

